language: csharp
dist: trusty
services:
  - docker
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
sudo: required
mono: none
dotnet: 2.0.2
os:
  - linux
script:
  - dotnet restore ./src/Autumn.Mvc.Data.sln
  - dotnet build ./src/Autumn.Mvc.Data.sln
  - dotnet test --no-build ./src/Autumn.Mvc.Data.Tests/Autumn.Mvc.Data.Tests.csproj