language: csharp
dist: trusty
services:
  - docker
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
sudo: required
mono: none
dotnet: 2.0.2
os:
  - linux
script:
  - dotnet restore ./src/Autumn.Mvc.Data.sln
  - dotnet build -c Release -v ./src/Autumn.Mvc.Data.sln
  - dotnet test --no-build ./src/Autumn.Mvc.Data.Tests/Autumn.Mvc.Data.Tests.csproj
  - dotnet pack -v --no-build --version-suffix "pre" /p:0.0.1 ./src/Autumn.Mvc.Data/Autumn.Mvc.Data.csproj 
  - dotnet nuget push *.nupkg -k a3f9189e-6aa8-4754-9fa9-50a46268db00 -s https://www.nuget.org/api/v2/package

	
