language: csharp
dist: trusty
services:
  - docker
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
sudo: required
mono: none
dotnet: 2.0.2
os:
  - linux
script:
  - dotnet restore ./src/Autumn.Mvc.Data.sln
  - dotnet build --configuration Release ./src/Autumn.Mvc.Data.sln

deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh $NUGET_API_KEY $NUGET_SOURCE 1.2.2
    on:
      branch: master	
