//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Rsql.g by ANTLR 4.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Autumn.Data.Mvc.Models.Queries {
using System;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6")]
[System.CLSCompliant(false)]
public partial class RsqlParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, LETTER=13, DIGIT=14, NUMBER=15, DATE=16, 
		ALPHA=17, ANY=18;
	public const int
		RULE_selector = 0, RULE_eval = 1, RULE_or = 2, RULE_and = 3, RULE_constraint = 4, 
		RULE_group = 5, RULE_comparison = 6, RULE_comparator = 7, RULE_comp_fiql = 8, 
		RULE_comp_alt = 9, RULE_reserved = 10, RULE_single_quote = 11, RULE_arguments = 12, 
		RULE_value = 13;
	public static readonly string[] ruleNames = {
		"selector", "eval", "or", "and", "constraint", "group", "comparison", 
		"comparator", "comp_fiql", "comp_alt", "reserved", "single_quote", "arguments", 
		"value"
	};

	private static readonly string[] _LiteralNames = {
		null, "'''", "'('", "')'", "';'", "','", "'='", "'~'", "'<'", "'>'", "' '", 
		"'-'", "'\\''"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, "LETTER", "DIGIT", "NUMBER", "DATE", "ALPHA", "ANY"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Rsql.g"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	static RsqlParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

	public RsqlParser(ITokenStream input)
		: base(input)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class SelectorContext : ParserRuleContext {
		public SelectorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_selector; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.EnterSelector(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.ExitSelector(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRsqlVisitor<TResult> typedVisitor = visitor as IRsqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSelector(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SelectorContext selector() {
		SelectorContext _localctx = new SelectorContext(Context, State);
		EnterRule(_localctx, 0, RULE_selector);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 29;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 28;
				_la = TokenStream.LA(1);
				if ( _la <= 0 || ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__1) | (1L << T__2) | (1L << T__3) | (1L << T__4) | (1L << T__5) | (1L << T__6) | (1L << T__7) | (1L << T__8) | (1L << T__9))) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				}
				State = 31;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__10) | (1L << T__11) | (1L << LETTER) | (1L << DIGIT) | (1L << NUMBER) | (1L << DATE) | (1L << ALPHA) | (1L << ANY))) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EvalContext : ParserRuleContext {
		public OrContext or() {
			return GetRuleContext<OrContext>(0);
		}
		public EvalContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_eval; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.EnterEval(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.ExitEval(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRsqlVisitor<TResult> typedVisitor = visitor as IRsqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEval(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EvalContext eval() {
		EvalContext _localctx = new EvalContext(Context, State);
		EnterRule(_localctx, 2, RULE_eval);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 33; or();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OrContext : ParserRuleContext {
		public AndContext[] and() {
			return GetRuleContexts<AndContext>();
		}
		public AndContext and(int i) {
			return GetRuleContext<AndContext>(i);
		}
		public OrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_or; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.EnterOr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.ExitOr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRsqlVisitor<TResult> typedVisitor = visitor as IRsqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OrContext or() {
		OrContext _localctx = new OrContext(Context, State);
		EnterRule(_localctx, 4, RULE_or);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 35; and();
			State = 40;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__4) {
				{
				{
				State = 36; Match(T__4);
				State = 37; and();
				}
				}
				State = 42;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AndContext : ParserRuleContext {
		public ConstraintContext[] constraint() {
			return GetRuleContexts<ConstraintContext>();
		}
		public ConstraintContext constraint(int i) {
			return GetRuleContext<ConstraintContext>(i);
		}
		public AndContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_and; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.EnterAnd(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.ExitAnd(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRsqlVisitor<TResult> typedVisitor = visitor as IRsqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAnd(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AndContext and() {
		AndContext _localctx = new AndContext(Context, State);
		EnterRule(_localctx, 6, RULE_and);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 43; constraint();
			State = 48;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__3) {
				{
				{
				State = 44; Match(T__3);
				State = 45; constraint();
				}
				}
				State = 50;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConstraintContext : ParserRuleContext {
		public GroupContext group() {
			return GetRuleContext<GroupContext>(0);
		}
		public ComparisonContext comparison() {
			return GetRuleContext<ComparisonContext>(0);
		}
		public ConstraintContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constraint; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.EnterConstraint(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.ExitConstraint(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRsqlVisitor<TResult> typedVisitor = visitor as IRsqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConstraint(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConstraintContext constraint() {
		ConstraintContext _localctx = new ConstraintContext(Context, State);
		EnterRule(_localctx, 8, RULE_constraint);
		try {
			State = 53;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 51; group();
				}
				break;
			case T__10:
			case T__11:
			case LETTER:
			case DIGIT:
			case NUMBER:
			case DATE:
			case ALPHA:
			case ANY:
				EnterOuterAlt(_localctx, 2);
				{
				State = 52; comparison();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GroupContext : ParserRuleContext {
		public OrContext or() {
			return GetRuleContext<OrContext>(0);
		}
		public GroupContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_group; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.EnterGroup(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.ExitGroup(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRsqlVisitor<TResult> typedVisitor = visitor as IRsqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGroup(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public GroupContext group() {
		GroupContext _localctx = new GroupContext(Context, State);
		EnterRule(_localctx, 10, RULE_group);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 55; Match(T__1);
			State = 56; or();
			State = 57; Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ComparisonContext : ParserRuleContext {
		public SelectorContext selector() {
			return GetRuleContext<SelectorContext>(0);
		}
		public ComparatorContext comparator() {
			return GetRuleContext<ComparatorContext>(0);
		}
		public ArgumentsContext arguments() {
			return GetRuleContext<ArgumentsContext>(0);
		}
		public ComparisonContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comparison; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.EnterComparison(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.ExitComparison(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRsqlVisitor<TResult> typedVisitor = visitor as IRsqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComparison(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ComparisonContext comparison() {
		ComparisonContext _localctx = new ComparisonContext(Context, State);
		EnterRule(_localctx, 12, RULE_comparison);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 59; selector();
			State = 60; comparator();
			State = 62;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__1) | (1L << DIGIT) | (1L << NUMBER) | (1L << DATE))) != 0)) {
				{
				State = 61; arguments();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ComparatorContext : ParserRuleContext {
		public Comp_fiqlContext comp_fiql() {
			return GetRuleContext<Comp_fiqlContext>(0);
		}
		public Comp_altContext comp_alt() {
			return GetRuleContext<Comp_altContext>(0);
		}
		public ComparatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comparator; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.EnterComparator(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.ExitComparator(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRsqlVisitor<TResult> typedVisitor = visitor as IRsqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComparator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ComparatorContext comparator() {
		ComparatorContext _localctx = new ComparatorContext(Context, State);
		EnterRule(_localctx, 14, RULE_comparator);
		try {
			State = 66;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__5:
				EnterOuterAlt(_localctx, 1);
				{
				State = 64; comp_fiql();
				}
				break;
			case T__7:
			case T__8:
				EnterOuterAlt(_localctx, 2);
				{
				State = 65; comp_alt();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Comp_fiqlContext : ParserRuleContext {
		public ITerminalNode[] ALPHA() { return GetTokens(RsqlParser.ALPHA); }
		public ITerminalNode ALPHA(int i) {
			return GetToken(RsqlParser.ALPHA, i);
		}
		public Comp_fiqlContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comp_fiql; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.EnterComp_fiql(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.ExitComp_fiql(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRsqlVisitor<TResult> typedVisitor = visitor as IRsqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComp_fiql(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Comp_fiqlContext comp_fiql() {
		Comp_fiqlContext _localctx = new Comp_fiqlContext(Context, State);
		EnterRule(_localctx, 16, RULE_comp_fiql);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 68; Match(T__5);
			State = 77;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ALPHA) {
				{
				State = 69; Match(ALPHA);
				State = 74;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__10) {
					{
					{
					State = 70; Match(T__10);
					State = 71; Match(ALPHA);
					}
					}
					State = 76;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 79; Match(T__5);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Comp_altContext : ParserRuleContext {
		public Comp_altContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comp_alt; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.EnterComp_alt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.ExitComp_alt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRsqlVisitor<TResult> typedVisitor = visitor as IRsqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComp_alt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Comp_altContext comp_alt() {
		Comp_altContext _localctx = new Comp_altContext(Context, State);
		EnterRule(_localctx, 18, RULE_comp_alt);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 81;
			_la = TokenStream.LA(1);
			if ( !(_la==T__7 || _la==T__8) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 83;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__5) {
				{
				State = 82; Match(T__5);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReservedContext : ParserRuleContext {
		public ReservedContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_reserved; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.EnterReserved(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.ExitReserved(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRsqlVisitor<TResult> typedVisitor = visitor as IRsqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReserved(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ReservedContext reserved() {
		ReservedContext _localctx = new ReservedContext(Context, State);
		EnterRule(_localctx, 20, RULE_reserved);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 85;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__1) | (1L << T__2) | (1L << T__3) | (1L << T__4) | (1L << T__5) | (1L << T__6) | (1L << T__7) | (1L << T__8) | (1L << T__9))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Single_quoteContext : ParserRuleContext {
		public Single_quoteContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_single_quote; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.EnterSingle_quote(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.ExitSingle_quote(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRsqlVisitor<TResult> typedVisitor = visitor as IRsqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSingle_quote(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Single_quoteContext single_quote() {
		Single_quoteContext _localctx = new Single_quoteContext(Context, State);
		EnterRule(_localctx, 22, RULE_single_quote);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 87; Match(T__0);
			State = 92;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__1) | (1L << T__2) | (1L << T__3) | (1L << T__4) | (1L << T__5) | (1L << T__6) | (1L << T__7) | (1L << T__8) | (1L << T__9) | (1L << T__10) | (1L << T__11) | (1L << LETTER) | (1L << DIGIT) | (1L << NUMBER) | (1L << DATE) | (1L << ALPHA) | (1L << ANY))) != 0)) {
				{
				State = 90;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
				case 1:
					{
					State = 88; Match(T__11);
					}
					break;
				case 2:
					{
					State = 89;
					_la = TokenStream.LA(1);
					if ( _la <= 0 || (_la==T__0) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					}
					break;
				}
				}
				State = 94;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 95; Match(T__0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentsContext : ParserRuleContext {
		public ValueContext[] value() {
			return GetRuleContexts<ValueContext>();
		}
		public ValueContext value(int i) {
			return GetRuleContext<ValueContext>(i);
		}
		public ArgumentsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arguments; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.EnterArguments(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.ExitArguments(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRsqlVisitor<TResult> typedVisitor = visitor as IRsqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArguments(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentsContext arguments() {
		ArgumentsContext _localctx = new ArgumentsContext(Context, State);
		EnterRule(_localctx, 24, RULE_arguments);
		int _la;
		try {
			State = 109;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 97; Match(T__1);
				State = 98; value();
				State = 103;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__4) {
					{
					{
					State = 99; Match(T__4);
					State = 100; value();
					}
					}
					State = 105;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 106; Match(T__2);
				}
				break;
			case T__0:
			case DIGIT:
			case NUMBER:
			case DATE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 108; value();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		public ITerminalNode DATE() { return GetToken(RsqlParser.DATE, 0); }
		public ITerminalNode NUMBER() { return GetToken(RsqlParser.NUMBER, 0); }
		public ITerminalNode DIGIT() { return GetToken(RsqlParser.DIGIT, 0); }
		public Single_quoteContext single_quote() {
			return GetRuleContext<Single_quoteContext>(0);
		}
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		public override void EnterRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.EnterValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IRsqlListener typedListener = listener as IRsqlListener;
			if (typedListener != null) typedListener.ExitValue(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRsqlVisitor<TResult> typedVisitor = visitor as IRsqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 26, RULE_value);
		try {
			State = 115;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DATE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 111; Match(DATE);
				}
				break;
			case NUMBER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 112; Match(NUMBER);
				}
				break;
			case DIGIT:
				EnterOuterAlt(_localctx, 3);
				{
				State = 113; Match(DIGIT);
				}
				break;
			case T__0:
				EnterOuterAlt(_localctx, 4);
				{
				State = 114; single_quote();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static string _serializedATN = _serializeATN();
	private static string _serializeATN()
	{
	    StringBuilder sb = new StringBuilder();
	    sb.Append("\x3\x430\xD6D1\x8206\xAD2D\x4417\xAEF1\x8D80\xAADD\x3\x14");
		sb.Append("x\x4\x2\t\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4");
		sb.Append("\a\t\a\x4\b\t\b\x4\t\t\t\x4\n\t\n\x4\v\t\v\x4\f\t\f\x4\r\t\r");
		sb.Append("\x4\xE\t\xE\x4\xF\t\xF\x3\x2\x6\x2 \n\x2\r\x2\xE\x2!\x3\x3\x3");
		sb.Append("\x3\x3\x4\x3\x4\x3\x4\a\x4)\n\x4\f\x4\xE\x4,\v\x4\x3\x5\x3\x5");
		sb.Append("\x3\x5\a\x5\x31\n\x5\f\x5\xE\x5\x34\v\x5\x3\x6\x3\x6\x5\x6\x38");
		sb.Append("\n\x6\x3\a\x3\a\x3\a\x3\a\x3\b\x3\b\x3\b\x5\b\x41\n\b\x3\t\x3");
		sb.Append("\t\x5\t\x45\n\t\x3\n\x3\n\x3\n\x3\n\a\nK\n\n\f\n\xE\nN\v\n\x5");
		sb.Append("\nP\n\n\x3\n\x3\n\x3\v\x3\v\x5\vV\n\v\x3\f\x3\f\x3\r\x3\r\x3");
		sb.Append("\r\a\r]\n\r\f\r\xE\r`\v\r\x3\r\x3\r\x3\xE\x3\xE\x3\xE\x3\xE");
		sb.Append("\a\xEh\n\xE\f\xE\xE\xEk\v\xE\x3\xE\x3\xE\x3\xE\x5\xEp\n\xE\x3");
		sb.Append("\xF\x3\xF\x3\xF\x3\xF\x5\xFv\n\xF\x3\xF\x2\x2\x10\x2\x4\x6\b");
		sb.Append("\n\f\xE\x10\x12\x14\x16\x18\x1A\x1C\x2\x5\x3\x2\x3\f\x3\x2\n");
		sb.Append("\v\x3\x2\x3\x3y\x2\x1F\x3\x2\x2\x2\x4#\x3\x2\x2\x2\x6%\x3\x2");
		sb.Append("\x2\x2\b-\x3\x2\x2\x2\n\x37\x3\x2\x2\x2\f\x39\x3\x2\x2\x2\xE");
		sb.Append("=\x3\x2\x2\x2\x10\x44\x3\x2\x2\x2\x12\x46\x3\x2\x2\x2\x14S\x3");
		sb.Append("\x2\x2\x2\x16W\x3\x2\x2\x2\x18Y\x3\x2\x2\x2\x1Ao\x3\x2\x2\x2");
		sb.Append("\x1Cu\x3\x2\x2\x2\x1E \n\x2\x2\x2\x1F\x1E\x3\x2\x2\x2 !\x3\x2");
		sb.Append("\x2\x2!\x1F\x3\x2\x2\x2!\"\x3\x2\x2\x2\"\x3\x3\x2\x2\x2#$\x5");
		sb.Append("\x6\x4\x2$\x5\x3\x2\x2\x2%*\x5\b\x5\x2&\'\a\a\x2\x2\')\x5\b");
		sb.Append("\x5\x2(&\x3\x2\x2\x2),\x3\x2\x2\x2*(\x3\x2\x2\x2*+\x3\x2\x2");
		sb.Append("\x2+\a\x3\x2\x2\x2,*\x3\x2\x2\x2-\x32\x5\n\x6\x2./\a\x6\x2\x2");
		sb.Append("/\x31\x5\n\x6\x2\x30.\x3\x2\x2\x2\x31\x34\x3\x2\x2\x2\x32\x30");
		sb.Append("\x3\x2\x2\x2\x32\x33\x3\x2\x2\x2\x33\t\x3\x2\x2\x2\x34\x32\x3");
		sb.Append("\x2\x2\x2\x35\x38\x5\f\a\x2\x36\x38\x5\xE\b\x2\x37\x35\x3\x2");
		sb.Append("\x2\x2\x37\x36\x3\x2\x2\x2\x38\v\x3\x2\x2\x2\x39:\a\x4\x2\x2");
		sb.Append(":;\x5\x6\x4\x2;<\a\x5\x2\x2<\r\x3\x2\x2\x2=>\x5\x2\x2\x2>@\x5");
		sb.Append("\x10\t\x2?\x41\x5\x1A\xE\x2@?\x3\x2\x2\x2@\x41\x3\x2\x2\x2\x41");
		sb.Append("\xF\x3\x2\x2\x2\x42\x45\x5\x12\n\x2\x43\x45\x5\x14\v\x2\x44");
		sb.Append("\x42\x3\x2\x2\x2\x44\x43\x3\x2\x2\x2\x45\x11\x3\x2\x2\x2\x46");
		sb.Append("O\a\b\x2\x2GL\a\x13\x2\x2HI\a\r\x2\x2IK\a\x13\x2\x2JH\x3\x2");
		sb.Append("\x2\x2KN\x3\x2\x2\x2LJ\x3\x2\x2\x2LM\x3\x2\x2\x2MP\x3\x2\x2");
		sb.Append("\x2NL\x3\x2\x2\x2OG\x3\x2\x2\x2OP\x3\x2\x2\x2PQ\x3\x2\x2\x2");
		sb.Append("QR\a\b\x2\x2R\x13\x3\x2\x2\x2SU\t\x3\x2\x2TV\a\b\x2\x2UT\x3");
		sb.Append("\x2\x2\x2UV\x3\x2\x2\x2V\x15\x3\x2\x2\x2WX\t\x2\x2\x2X\x17\x3");
		sb.Append("\x2\x2\x2Y^\a\x3\x2\x2Z]\a\xE\x2\x2[]\n\x4\x2\x2\\Z\x3\x2\x2");
		sb.Append("\x2\\[\x3\x2\x2\x2]`\x3\x2\x2\x2^\\\x3\x2\x2\x2^_\x3\x2\x2\x2");
		sb.Append("_\x61\x3\x2\x2\x2`^\x3\x2\x2\x2\x61\x62\a\x3\x2\x2\x62\x19\x3");
		sb.Append("\x2\x2\x2\x63\x64\a\x4\x2\x2\x64i\x5\x1C\xF\x2\x65\x66\a\a\x2");
		sb.Append("\x2\x66h\x5\x1C\xF\x2g\x65\x3\x2\x2\x2hk\x3\x2\x2\x2ig\x3\x2");
		sb.Append("\x2\x2ij\x3\x2\x2\x2jl\x3\x2\x2\x2ki\x3\x2\x2\x2lm\a\x5\x2\x2");
		sb.Append("mp\x3\x2\x2\x2np\x5\x1C\xF\x2o\x63\x3\x2\x2\x2on\x3\x2\x2\x2");
		sb.Append("p\x1B\x3\x2\x2\x2qv\a\x12\x2\x2rv\a\x11\x2\x2sv\a\x10\x2\x2");
		sb.Append("tv\x5\x18\r\x2uq\x3\x2\x2\x2ur\x3\x2\x2\x2us\x3\x2\x2\x2ut\x3");
		sb.Append("\x2\x2\x2v\x1D\x3\x2\x2\x2\x10!*\x32\x37@\x44LOU\\^iou");
	    return sb.ToString();
	}

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());


}
} // namespace Autumn.Data.Mvc.Models.Queries
