faker.locale = "en"

const STEPCOUNT = 100; //total 1000 * 100 = 100000

function isRandomBlank(blankWeight) {
    return Math.random() * 100 <= blankWeight;
};

for (let i = 0; i < 1000; i++) {
    db.getCollection("company").insertMany(
        _.times(STEPCOUNT, () => {
            return {
                "name": faker.company.companyName(),
                "suffixes": faker.company.suffixes()
            }
        })
    )

    console.log(`${(i + 1) * STEPCOUNT} docs inserted`);
}
